// Auto-generated by scripts/generate-build-tags.mjs. Do not edit manually.
(function (root) {
  var info = {
    version: "3.26.9",
    buildTag: "cand-3.26.9-4686c698c0",
    builtAt: "2026-10-03T06:37:20.914Z"
  };
  if (typeof self !== "undefined") {
    self.__LPTFF_EXTENSION_BUILD_INFO__ = info;
  }
  if (typeof window !== "undefined") {
    window.__LPTFF_EXTENSION_BUILD_INFO__ = info;
  }
})(typeof globalThis !== "undefined" ? globalThis : this);
