// Auto-generated by scripts/generate-build-tags.mjs. Do not edit manually.
(function (root) {
  var info = {
    version: "3.25.0",
    buildTag: "cand-3.25.0-3aff2554ad",
    builtAt: "2026-09-21T12:58:18.578Z"
  };
  if (typeof self !== "undefined") {
    self.__LPTFF_EXTENSION_BUILD_INFO__ = info;
  }
  if (typeof window !== "undefined") {
    window.__LPTFF_EXTENSION_BUILD_INFO__ = info;
  }
})(typeof globalThis !== "undefined" ? globalThis : this);
