// Auto-generated by project-support/scripts/generate-build-tags.mjs. Do not edit manually.
(function (root) {
  var info = {
    version: "3.25.0",
    buildTag: "cand-3.25.0-ece2eceafd",
    builtAt: "2026-09-13T14:50:06.378Z"
  };
  if (typeof self !== "undefined") {
    self.__LPTFF_EXTENSION_BUILD_INFO__ = info;
  }
  if (typeof window !== "undefined") {
    window.__LPTFF_EXTENSION_BUILD_INFO__ = info;
  }
})(typeof globalThis !== "undefined" ? globalThis : this);
