// Auto-generated by scripts/generate-build-tags.mjs. Do not edit manually.
export const WEB_BUILD_TAG = "cand-web-17fd23e737";
export const EXPECTED_EXTENSION_BUILD_TAG = "cand-3.26.7-8abefe9a82";
export const EXTENSION_VERSION = "3.26.7";
export const BUILT_AT = "2026-10-03T06:04:06.612Z";
