// Auto-generated by scripts/generate-build-tags.mjs. Do not edit manually.
export const WEB_BUILD_TAG = "cand-web-17fd23e737";
export const EXPECTED_EXTENSION_BUILD_TAG = "cand-3.26.9-4686c698c0";
export const EXTENSION_VERSION = "3.26.9";
export const BUILT_AT = "2026-10-03T06:37:20.914Z";
