# Simple workflow for deploying static content to GitHub Pages
name: CI
on:
  # 仅在推送到默认分支时运行。
  push:
    branches: 
      - master

  # 这个选项可以使你手动在 Action tab 页面触发工作流
  workflow_dispatch:      

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages。
permissions:
  contents: read
  pages: write
  id-token: write

# 允许一个并发的部署
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # 单次部署的工作描述
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: echo filepath
        run: |
          pwd
          ls -al
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      # - name: Build
      #   run: 
      #     npm run build
      # - name: 404
      #   run: 
      #     cp dist/index.html dist/404.html
      - name: Build
        run: 
          npm run docs:build
      # - name: Setup Pages
      #   uses: actions/configure-pages@v3
      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v1
      #   with:
          # path: './docs/.vuepress/dist'
      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   uses: actions/deploy-pages@v1
      - name: Deploy to GitHub Pages
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
        run: |
          cd ./docs/.vuepress/dist/
          echo tff.cn > CNAME  
          echo > .nojekyll
          git config --global user.name "LPTFF"
          git config --global user.email lptffhh@gmail.com
          git config --global init.defaultBranch master
          git init
          git add -A
          git commit -m "Auto Deploy"
          git remote set-url origin git@github.com:eurydyce/MDANSE.git
          git push -f "https://LPTFF:${{ secrets.ACCESS_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" HEAD:gh-pages