# Simple workflow for deploying static content to GitHub Pages
name: CI
on:
  push:
    branches:
      - master

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: crawl
        run: |
          chmod +x build.sh
          ./build.sh
          python  ./src/crawl/sendNotify.py
          cd ./src/public/data/
          git config --global user.email "lptffhh@gmail.com"
          git config --global user.name "LPTFF"
          git config --global init.defaultBranch master
          git init
          git add -A
          git commit -m $(date +%F日%H时%M分%S秒)
          git push -f "https://LPTFF:${{ secrets.ACCESS_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" HEAD:python-crawl
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          QYWX_KEY: ${{ secrets.QYWX_KEY }}
      - name: Build
        run: |
          npm run build
      - name: 404
        run: cp dist/index.html dist/404.html
      - name: Deploy
        run: |
          cd ./dist/
          echo lptff.github.io > CNAME
          echo > .nojekyll
          git config --global user.email "lptffhh@gmail.com"
          git config --global user.name "LPTFF"
          git config --global init.defaultBranch master
          git init
          git add -A
          git commit -m $(date +%F日%H时%M分%S秒)
          git push -f "https://LPTFF:${{ secrets.ACCESS_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" HEAD:gh-pages